name: Pruebas unitarias
on:
  push:
    branches: [ master ]
jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    steps:
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7'
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest discover -s tests -v